# Generated by Django 3.1.4 on 2021-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_image', models.CharField(max_length=2000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
    ]
