# Generated by Django 3.1.4 on 2020-12-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=25)),
                ('product_description', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
