# Generated by Django 3.1.4 on 2020-12-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201228_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='product_id',
        ),
        migrations.AddField(
            model_name='tuote',
            name='product_tags',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tuote',
            name='product_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tuote',
            name='product_image',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tuote',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
    ]
