# Generated by Django 3.1.4 on 2020-12-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201228_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='product_tags',
        ),
    ]
