# Generated by Django 3.1.4 on 2020-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_tuote_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuote',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
