# Generated by Django 3.1.4 on 2020-12-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_tuote_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuote',
            name='id',
        ),
        migrations.AddField(
            model_name='tuote',
            name='product_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
